Fix archetype quote and Definition classname on sample
cucumber/website pull request #74
Opened 2024-12-28 18:07 UTC by fabriceyopa

### 🤔 What's changed?

This change made easy to copy and paste example from the Cucumber project archetype.

### ⚡️ What's your motivation? 

I want to make it easy to follow the documentation

### 🏷️ What kind of change is this?

- :book: Documentation (improvements without changing code)

### ♻️ Anything particular you want feedback on?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://github.com/cucumber/.github/tree/main?tab=coc-ov-file)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

2024-12-29 16:13 UTC, davidjgoss requested changes
Thanks for taking the time @fabriceyopa.

Whilst the class rename makes sense, there are many other usages of it in the page, both in Java code samples and in console output (stack traces etc) - would you be able to update these too?

2024-12-29 17:53 UTC, fabriceyopa commented
Hello @davidjgoss ,
Sure going to update this ASAP.

2024-12-31 14:56 UTC, fabriceyopa commented
Hello @davidjgoss ,

I made some changes for the Java error logs and code sample.
Going to make another MR when try with Kotlin.

2025-01-08 00:05 UTC, davidjgoss approved these changes

2025-01-08 00:05 UTC, merged